version: "3.8"

services:
  # ────────── Ollama (official image) ───────────────────────────────
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./entrypoint-ollama.sh:/entrypoint-ollama.sh:ro
    restart: unless-stopped
    entrypoint: ["/entrypoint-ollama.sh"]

  # ────────── Spring-Boot chatbot ──────────────────────────────────
  chatbot:
    build:
      context: ./chatbot
      dockerfile: ../Dockerfile
    container_name: chatbot
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      - SPRING_OLLAMA_URL=http://ollama:11434/api/generate

volumes:
  ollama-data:
