ollama:
  url: "${SPRING_OLLAMA_URL:http://ollama:11434/api/generate}"
  model: llama3.2:1b
  stream: false
  temperature: 0.3
  num_predict: 100
  presence_penalty: 1.5


logging:
  level:
    root: INFO
    com.giannisdal.chatbot: DEBUG